services:
  app:
    command: bash -c "bundle exec rails db:prepare && bundle exec rails s -b 0.0.0.0"
    build: .
    container_name: app
    volumes:
      - .:/usr/src/task-manager
    expose:
      - "3000"
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE: ${DATABASE}
      DATABASE_TEST: ${DATABASE_TEST}
      DBUSER: ${POSTGRES_USER}
      DBPASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - database
    networks:
      - task_manager_network
  database:
    image: postgres:alpine
    container_name: database
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:54321:5432"
    networks:
      - task_manager_network

volumes:
  postgresql:

networks:
  task_manager_network:
