services:
  app:
    command: bash -c "bundle exec rails db:prepare && rails assets:precompile && bundle exec rails s -b 0.0.0.0"
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    volumes:
      - .:/usr/src/task-manager
    expose:
      - "3000"
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE: ${DATABASE}
      DATABASE_TEST: ${DATABASE_TEST}
      DBUSER: ${POSTGRES_USER}
      DBPASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - database
    networks:
      - task_manager_network
  database:
    image: postgres:alpine
    container_name: database
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "127.0.0.1:54321:5432"
    networks:
      - task_manager_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - task_manager_network

volumes:
  postgresql:
  redis_data:
    driver: local

networks:
  task_manager_network:
    driver: bridge